const { icons } = require("lucide");
const { writeFileSync, readFileSync } = require("node:fs");
const names = ["CalendarDays", "Inbox", "Monitor", "Plus", "Pencil", "Trash2", "X", "ChevronLeft", "ChevronRight", "ChevronDown", "Send", "Printer", "Maximize", "ArrowLeft", "MapPin", "Check", "Pause", "Play", "Bell"];
const reactAttributes = attrs => Object.fromEntries(Object.entries(attrs).map(([key, value]) => [key.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase()), value]));
const selected = Object.fromEntries(names.map(name => {
  const [tag, attrs, children] = icons[name];
  return [name, [tag, reactAttributes(attrs), children.map(([child, props]) => [child, reactAttributes(props)])]];
}));
writeFileSync("components/icons.js", "// Generated by npm run icons. Lucide, ISC license: https://lucide.dev/license\nwindow.TREELINE_ICONS = " + JSON.stringify(selected) + ";\n");
writeFileSync("components/icons.LICENSE.txt", readFileSync("node_modules/lucide/LICENSE"));
